/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internalPages;

import java.awt.Color;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author RageKing
 */
public class login extends javax.swing.JInternalFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        email = new javax.swing.JLabel();
        emailfield = new javax.swing.JTextField();
        pass = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        login = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        newuser = new javax.swing.JLabel();
        signup = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        upper = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();

        jPanel6.setBackground(new java.awt.Color(255, 204, 153));
        jPanel6.setLayout(null);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setMinimumSize(new java.awt.Dimension(450, 512));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        email.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        email.setText("Email");
        jPanel7.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 380, 20));

        emailfield.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        emailfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        emailfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        emailfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailfieldActionPerformed(evt);
            }
        });
        jPanel7.add(emailfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 370, 40));

        pass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pass.setText("Password");
        jPanel7.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 380, 20));

        jPasswordField1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPasswordField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 370, 40));

        login.setBackground(new java.awt.Color(255, 153, 102));
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginMouseExited(evt);
            }
        });
        login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Login");
        login.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 82, 40));

        jPanel7.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 110, 40));

        newuser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        newuser.setText("New user?");
        jPanel7.add(newuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 470, 100, -1));

        signup.setBackground(new java.awt.Color(255, 153, 102));
        signup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signupMouseExited(evt);
            }
        });
        signup.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Sign Up");
        signup.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 30));

        jPanel7.add(signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, 90, 30));

        upper.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        upper.setForeground(new java.awt.Color(0, 0, 102));
        upper.setText("LOGIN");
        upper.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel7.add(upper, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 269, 88));

        jPanel6.add(jPanel7);
        jPanel7.setBounds(560, 10, 439, 540);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/logosmall-removebg-preview.png"))); // NOI18N
        jPanel6.add(logo);
        logo.setBounds(-30, 90, 691, 361);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 1040, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailfieldActionPerformed

    private void loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseEntered
        login.setBackground(new Color(255,204,153));
    }//GEN-LAST:event_loginMouseEntered

    private void loginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseExited
        login.setBackground(new Color(255,153,102));
    }//GEN-LAST:event_loginMouseExited

    private void signupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupMouseEntered
        signup.setBackground(new Color(255,204,153));
    }//GEN-LAST:event_signupMouseEntered

    private void signupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupMouseExited
        signup.setBackground(new Color(255,153,102));
    }//GEN-LAST:event_signupMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel email;
    private javax.swing.JTextField emailfield;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPanel login;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel newuser;
    private javax.swing.JLabel pass;
    private javax.swing.JPanel signup;
    private javax.swing.JLabel upper;
    // End of variables declaration//GEN-END:variables
}
