/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internalPages;

import static com.sun.deploy.uitoolkit.impl.fx.ui.MixedCodeInSwing.show;
import config.*;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.JOptionPane;

/**
 *
 * @author RageKing
 */
public class register extends javax.swing.JInternalFrame {

    /**
     * Creates new form register
     */
    public register() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        container = new javax.swing.JPanel();
        loghead = new javax.swing.JLabel();
        emlabel = new javax.swing.JLabel();
        em = new javax.swing.JTextField();
        passlabel = new javax.swing.JLabel();
        eye = new javax.swing.JLabel();
        ps = new javax.swing.JPasswordField();
        botcreate = new javax.swing.JPanel();
        create = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        login = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        fullname = new javax.swing.JTextField();
        pic1 = new javax.swing.JLabel();
        van = new javax.swing.JLabel();
        pic2 = new javax.swing.JLabel();
        pic3 = new javax.swing.JLabel();
        pic4 = new javax.swing.JLabel();
        pic5 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        container.setBackground(new java.awt.Color(209, 232, 243));
        container.setLayout(null);

        loghead.setFont(new java.awt.Font("Arial Narrow", 1, 36)); // NOI18N
        loghead.setForeground(new java.awt.Color(51, 153, 255));
        loghead.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loghead.setText("SIGN IN");
        loghead.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        container.add(loghead);
        loghead.setBounds(0, 0, 570, 80);

        emlabel.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        emlabel.setForeground(new java.awt.Color(51, 153, 255));
        emlabel.setText("Email*");
        container.add(emlabel);
        emlabel.setBounds(70, 160, 270, 30);

        em.setForeground(new java.awt.Color(51, 153, 255));
        em.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        em.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        em.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emActionPerformed(evt);
            }
        });
        container.add(em);
        em.setBounds(70, 190, 450, 40);

        passlabel.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        passlabel.setForeground(new java.awt.Color(51, 153, 255));
        passlabel.setText("Password*");
        container.add(passlabel);
        passlabel.setBounds(70, 241, 90, 30);

        eye.setBackground(new java.awt.Color(255, 255, 255));
        eye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/eye.png"))); // NOI18N
        eye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eyeMouseClicked(evt);
            }
        });
        container.add(eye);
        eye.setBounds(490, 280, 30, 20);

        ps.setForeground(new java.awt.Color(51, 153, 255));
        ps.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ps.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));
        container.add(ps);
        ps.setBounds(70, 270, 450, 40);

        botcreate.setBackground(new java.awt.Color(152, 209, 247));
        botcreate.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botcreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botcreateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botcreateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botcreateMouseExited(evt);
            }
        });
        botcreate.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                botcreateInputMethodTextChanged(evt);
            }
        });
        botcreate.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        create.setBackground(new java.awt.Color(255, 255, 255));
        create.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        create.setForeground(new java.awt.Color(255, 255, 255));
        create.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        create.setText("Create account");
        create.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createMouseClicked(evt);
            }
        });
        botcreate.add(create, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 40));

        container.add(botcreate);
        botcreate.setBounds(70, 340, 450, 40);

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setText(" Already have an account? ");
        container.add(jLabel1);
        jLabel1.setBounds(140, 410, 188, 21);

        login.setBackground(new java.awt.Color(255, 255, 255));
        login.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        login.setForeground(new java.awt.Color(51, 153, 255));
        login.setText("Login");
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginMouseExited(evt);
            }
        });
        container.add(login);
        login.setBounds(330, 410, 130, 21);

        name.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        name.setForeground(new java.awt.Color(51, 153, 255));
        name.setText("Full Name*");
        container.add(name);
        name.setBounds(70, 70, 160, 50);

        fullname.setForeground(new java.awt.Color(51, 153, 255));
        fullname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fullname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        fullname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullnameActionPerformed(evt);
            }
        });
        container.add(fullname);
        fullname.setBounds(70, 110, 450, 40);

        jPanel1.add(container, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 570, 450));

        pic1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/leah.jpg"))); // NOI18N
        jPanel1.add(pic1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 300, 250));

        van.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/vann.JPG"))); // NOI18N
        jPanel1.add(van, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 540, 380));

        pic2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/temple.jpg"))); // NOI18N
        jPanel1.add(pic2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 250, 200));

        pic3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/night.jpg"))); // NOI18N
        jPanel1.add(pic3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 270, 160));

        pic4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/night1.jpg"))); // NOI18N
        jPanel1.add(pic4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 520, 160));

        pic5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/temple1.jpg"))); // NOI18N
        jPanel1.add(pic5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, -50, 1120, 850));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -16, 1090, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emActionPerformed

    private void eyeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eyeMouseClicked

        ps.add(eye).setVisible(true);
    }//GEN-LAST:event_eyeMouseClicked

    private void botcreateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botcreateMouseEntered
        botcreate.setBackground(new Color(51,102,255));
    }//GEN-LAST:event_botcreateMouseEntered

    private void botcreateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botcreateMouseExited
        botcreate.setBackground(new Color(152,209,247));
    }//GEN-LAST:event_botcreateMouseExited

    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
            Signin s = new Signin();
            s.setVisible(true);
            dispose();
    }//GEN-LAST:event_loginMouseClicked

    private void loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseEntered
        login.setForeground(new Color(0,0,153));
    }//GEN-LAST:event_loginMouseEntered

    private void loginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseExited
        login.setForeground(new Color(51,153,255));
    }//GEN-LAST:event_loginMouseExited

    private void fullnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullnameActionPerformed

    private void botcreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botcreateMouseClicked
         
       
       
    }//GEN-LAST:event_botcreateMouseClicked

    private void createMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createMouseClicked
       
        
            String nameInput = fullname.getText().trim();
            String emailInput = em.getText().trim();
            String passwordInput = ps.getText().trim();

            // Check if fields are empty
            if (nameInput.isEmpty() || emailInput.isEmpty() || passwordInput.isEmpty()) {
                JOptionPane.showMessageDialog(null, 
                    "All fields are required!", 
                    "Validation Error", 
                    JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Check email format
            if (!emailInput.matches("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$")) {
                JOptionPane.showMessageDialog(null, 
                    "Enter a valid email!\nExample: name@email.com", 
                    "Validation Error", 
                    JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Check password length
            if (passwordInput.length() < 6) {
                JOptionPane.showMessageDialog(null, 
                    "Password must be at least 6 characters!", 
                    "Validation Error", 
                    JOptionPane.ERROR_MESSAGE);
                return;
            }

            try {
                config con = new config();

                // Check if email already exists
                ResultSet rs = con.getData("SELECT * FROM tbl_accounts WHERE email = ?", emailInput);

                if (rs != null && rs.next()) {
                    JOptionPane.showMessageDialog(null, 
                        "Email '" + emailInput + "' already exists!\nUse a different email.", 
                        "Email Already Exists", 
                        JOptionPane.ERROR_MESSAGE);
                    return;
                }

                // Insert record
                con.addRecord(
                    "INSERT INTO tbl_accounts (name, email, password, type, status) VALUES (?, ?, ?, ?, ?)", 
                    nameInput, emailInput, passwordInput, "USER", "ACTIVE"
                );

                JOptionPane.showMessageDialog(null, 
                    "Account Created Successfully!", 
                    "Success", 
                    JOptionPane.INFORMATION_MESSAGE);

                // Clear fields
                fullname.setText("");
                em.setText("");
                ps.setText("");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, 
                    "Error: " + e.getMessage(), 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_createMouseClicked

    private void botcreateInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_botcreateInputMethodTextChanged
        
    }//GEN-LAST:event_botcreateInputMethodTextChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botcreate;
    private javax.swing.JPanel container;
    private javax.swing.JLabel create;
    private javax.swing.JTextField em;
    private javax.swing.JLabel emlabel;
    private javax.swing.JLabel eye;
    private javax.swing.JTextField fullname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel loghead;
    private javax.swing.JLabel login;
    private javax.swing.JLabel name;
    private javax.swing.JLabel passlabel;
    private javax.swing.JLabel pic1;
    private javax.swing.JLabel pic2;
    private javax.swing.JLabel pic3;
    private javax.swing.JLabel pic4;
    private javax.swing.JLabel pic5;
    private javax.swing.JPasswordField ps;
    private javax.swing.JLabel van;
    // End of variables declaration//GEN-END:variables
}
