/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internalPages;

import config.config;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author RageKing
 */
public class register extends javax.swing.JInternalFrame {

    /**
     * Creates new form register
     */
    public register() {
        initComponents();
         this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        upper = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        namepane = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        fullname = new javax.swing.JTextField();
        emailpane = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        password = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        signup = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        already = new javax.swing.JLabel();
        login = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        LOGO = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1011, 600));
        setVerifyInputWhenFocusTarget(false);

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));
        jPanel1.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jPanel1.setPreferredSize(new java.awt.Dimension(1011, 600));
        jPanel1.setVerifyInputWhenFocusTarget(false);
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        upper.setBackground(new java.awt.Color(255, 255, 255));
        upper.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("SIGN UP");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setMaximumSize(new java.awt.Dimension(100, 37));
        jLabel1.setMinimumSize(new java.awt.Dimension(100, 37));
        jLabel1.setPreferredSize(new java.awt.Dimension(100, 37));
        upper.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 269, 88));

        jPanel2.add(upper, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 450, 140));

        namepane.setBackground(new java.awt.Color(255, 255, 255));
        namepane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Full Name");
        namepane.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 11, -1, -1));

        jPanel2.add(namepane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 450, 40));

        fullname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fullname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fullname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fullnameMouseClicked(evt);
            }
        });
        fullname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullnameActionPerformed(evt);
            }
        });
        jPanel2.add(fullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 370, 40));

        emailpane.setBackground(new java.awt.Color(255, 255, 255));
        emailpane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Email");
        emailpane.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 380, 20));

        jPanel2.add(emailpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 390, 40));

        email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 370, 40));

        password.setBackground(new java.awt.Color(255, 255, 255));
        password.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Password");
        password.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 86, -1));

        jPanel2.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 370, 40));

        pass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });
        jPanel2.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 370, 40));

        signup.setBackground(new java.awt.Color(255, 153, 102));
        signup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signupMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signupMouseExited(evt);
            }
        });
        signup.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Sign Up");
        signup.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 82, 40));

        jPanel2.add(signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 110, 40));

        already.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        already.setText("Already have account");
        jPanel2.add(already, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 490, 170, -1));

        login.setBackground(new java.awt.Color(255, 153, 102));
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginMouseExited(evt);
            }
        });
        login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Login");
        login.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 30));

        jPanel2.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, 90, 30));

        jPanel1.add(jPanel2);
        jPanel2.setBounds(560, 20, 440, 530);

        LOGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/logosmall-removebg-preview.png"))); // NOI18N
        jPanel1.add(LOGO);
        LOGO.setBounds(-30, 90, 691, 361);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1067, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed

    }//GEN-LAST:event_passActionPerformed

    private void signupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupMouseEntered
        signup.setBackground(new Color(255,204,153));
    }//GEN-LAST:event_signupMouseEntered

    private void signupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupMouseExited
        signup.setBackground(new Color(255,153,102));
    }//GEN-LAST:event_signupMouseExited

    private void loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseEntered
        login.setBackground(new Color(255,204,153));
    }//GEN-LAST:event_loginMouseEntered

    private void loginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseExited
        login.setBackground(new Color(255,153,102));
    }//GEN-LAST:event_loginMouseExited

    private void fullnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullnameActionPerformed

    private void fullnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fullnameMouseClicked
       config con = new config();
       
       String sql = "INSERT INTO tbl_accounts (name, email , pass ,type ,status)  VALUES (?, ?, ?, ?, ?)";
       con.addRecord(sql, fullname.getText(), email.getText(), pass.getText(),"Admin","Pending");
       JOptionPane.showMessageDialog(null, "RECORD ADDED!");
    }//GEN-LAST:event_fullnameMouseClicked

    private void signupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupMouseClicked
        config con = new config();
       
       String sql = "INSERT INTO tbl_accounts (name, email , pass ,type ,status)  VALUES (?, ?, ?, ?, ?)";
       con.addRecord(sql, fullname.getText(), email.getText(), pass.getText(),"Admin","Pending");
       JOptionPane.showMessageDialog(null, "RECORD ADDED!");
    }//GEN-LAST:event_signupMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LOGO;
    private javax.swing.JLabel already;
    private javax.swing.JTextField email;
    private javax.swing.JPanel emailpane;
    private javax.swing.JTextField fullname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel login;
    private javax.swing.JPanel namepane;
    private javax.swing.JPasswordField pass;
    private javax.swing.JPanel password;
    private javax.swing.JPanel signup;
    private javax.swing.JPanel upper;
    // End of variables declaration//GEN-END:variables
}
