/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internalPages;

import admin.adminDashboard;
import config.config;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import superadmin.superadminDashboard;
import user.userDashboard;

/**
 *
 * @author RageKing
 */
public class Signin extends javax.swing.JInternalFrame {

    /**
     * 
     */
    public Signin() {
        initComponents();
        createDefaultAccount();
        
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
    }
    
    
    private void createDefaultAccount() {
    config con = new config();
    
    // Check if default admin exists
    String checkQuery = "SELECT * FROM tbl_accounts WHERE email = ? AND type = ?";
    String exists = con.authenticate(checkQuery, "superadmin@gmail.com", "SUPERADMIN");
    
    if(exists == null) {
        // Default account doesn't exist, create it
        String insertQuery = "INSERT INTO tbl_accounts (email, password, status, type) VALUES (?, ?, ?, ?)";
        
        try (Connection conn = con.connectDB();
             PreparedStatement pstmt = conn.prepareStatement(insertQuery)) {
            
            pstmt.setString(1, "superadmin@gmail.com");
            pstmt.setString(2, "super123"); // Change this to your preferred password
            pstmt.setString(3, "ACTIVE");
            pstmt.setString(4, "SUPERADMIN");
            
            pstmt.executeUpdate();
            System.out.println("Default superadmin account created successfully!");
            
        } catch (SQLException e) {
            System.out.println("Error creating default account: " + e.getMessage());
        }
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mainpane = new javax.swing.JDesktopPane();
        container = new javax.swing.JPanel();
        loghead = new javax.swing.JLabel();
        emlabel = new javax.swing.JLabel();
        em = new javax.swing.JTextField();
        passlabel = new javax.swing.JLabel();
        eye = new javax.swing.JLabel();
        ps = new javax.swing.JPasswordField();
        botlog = new javax.swing.JPanel();
        login = new javax.swing.JLabel();
        forget = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        register = new javax.swing.JLabel();
        van = new javax.swing.JLabel();
        beach = new javax.swing.JLabel();
        people = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));
        jPanel1.setLayout(null);

        mainpane.setBackground(new java.awt.Color(102, 204, 255));

        container.setBackground(new java.awt.Color(209, 232, 243));
        container.setLayout(null);

        loghead.setFont(new java.awt.Font("Arial Narrow", 1, 36)); // NOI18N
        loghead.setForeground(new java.awt.Color(51, 153, 255));
        loghead.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loghead.setText("LOGIN");
        loghead.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        container.add(loghead);
        loghead.setBounds(0, 0, 580, 80);

        emlabel.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        emlabel.setForeground(new java.awt.Color(51, 153, 255));
        emlabel.setText("Email*");
        container.add(emlabel);
        emlabel.setBounds(70, 100, 270, 40);

        em.setForeground(new java.awt.Color(51, 153, 255));
        em.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        em.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        em.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emActionPerformed(evt);
            }
        });
        container.add(em);
        em.setBounds(70, 140, 450, 40);

        passlabel.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        passlabel.setForeground(new java.awt.Color(51, 153, 255));
        passlabel.setText("Password*");
        container.add(passlabel);
        passlabel.setBounds(70, 200, 90, 21);

        eye.setBackground(new java.awt.Color(255, 255, 255));
        eye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/eye.png"))); // NOI18N
        eye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eyeMouseClicked(evt);
            }
        });
        container.add(eye);
        eye.setBounds(490, 240, 30, 20);

        ps.setForeground(new java.awt.Color(51, 153, 255));
        ps.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ps.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));
        container.add(ps);
        ps.setBounds(70, 230, 450, 40);

        botlog.setBackground(new java.awt.Color(152, 209, 247));
        botlog.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botlog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botlogMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botlogMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botlogMouseExited(evt);
            }
        });
        botlog.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login.setBackground(new java.awt.Color(255, 255, 255));
        login.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login.setText("Login");
        botlog.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 40));

        container.add(botlog);
        botlog.setBounds(70, 290, 450, 40);

        forget.setBackground(new java.awt.Color(255, 255, 255));
        forget.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        forget.setForeground(new java.awt.Color(51, 153, 255));
        forget.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        forget.setText("Forgot password?");
        forget.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                forgetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                forgetMouseExited(evt);
            }
        });
        container.add(forget);
        forget.setBounds(370, 190, 150, 40);

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setText(" Dont have an account? ");
        container.add(jLabel1);
        jLabel1.setBounds(130, 370, 180, 21);

        register.setBackground(new java.awt.Color(255, 255, 255));
        register.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        register.setForeground(new java.awt.Color(51, 153, 255));
        register.setText("Click to Register");
        register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registerMouseExited(evt);
            }
        });
        container.add(register);
        register.setBounds(300, 370, 130, 21);

        mainpane.add(container);
        container.setBounds(240, 50, 570, 410);

        van.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/van.jpeg"))); // NOI18N
        mainpane.add(van);
        van.setBounds(-160, -70, 800, 700);

        beach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/moalboal.jpg"))); // NOI18N
        mainpane.add(beach);
        beach.setBounds(630, 0, 390, 230);

        people.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/moal.jpg"))); // NOI18N
        mainpane.add(people);
        people.setBounds(10, 230, 1010, 330);

        jPanel1.add(mainpane);
        mainpane.setBounds(-10, 0, 1020, 550);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emActionPerformed

    private void eyeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eyeMouseClicked

        ps.add(eye).setVisible(true);
    }//GEN-LAST:event_eyeMouseClicked

    private void botlogMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botlogMouseEntered
        botlog.setBackground(new Color(51,102,255));
    }//GEN-LAST:event_botlogMouseEntered

    private void botlogMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botlogMouseExited
        botlog.setBackground(new Color(152,209,247));
    }//GEN-LAST:event_botlogMouseExited

    private void forgetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgetMouseEntered
        forget.setForeground(new Color(0,0,153));
    }//GEN-LAST:event_forgetMouseEntered

    private void forgetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgetMouseExited
        forget.setForeground(new Color(51,153,255));
    }//GEN-LAST:event_forgetMouseExited

    private void registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMouseClicked
        register r = new register();
        mainpane.add(r).setVisible(true);
    }//GEN-LAST:event_registerMouseClicked

    private void registerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMouseEntered
        register.setForeground(new Color(0,0,153));
    }//GEN-LAST:event_registerMouseEntered

    private void registerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMouseExited
        register.setForeground(new Color(51,153,255));
    }//GEN-LAST:event_registerMouseExited

    private void botlogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botlogMouseClicked
    
    config con = new config();
    String query = "SELECT type FROM tbl_accounts WHERE email = ? AND password = ? AND status = ?";
    
    String userType = con.authenticate(query, em.getText(), ps.getText(), "ACTIVE");
    
    if(userType != null){
        JOptionPane.showMessageDialog(null, "LOGIN SUCCESS!");
        
        mainpane.removeAll();
        
        if(userType.equalsIgnoreCase("SUPERADMIN")) {
            superadminDashboard sad = new superadminDashboard();
            mainpane.add(sad).setVisible(true);
            
        } else if(userType.equalsIgnoreCase("ADMIN")) {
            adminDashboard ad = new adminDashboard();
            mainpane.add(ad).setVisible(true);
            
        } else if(userType.equalsIgnoreCase("USER")) {
            userDashboard ud = new userDashboard();
            mainpane.add(ud).setVisible(true);
            
        } else {
            JOptionPane.showMessageDialog(null, "Unknown account type!");
        }
        
        mainpane.repaint();
        mainpane.revalidate();
        
        // Clear fields
        em.setText("");
        ps.setText("");
        
    } else {
        JOptionPane.showMessageDialog(null, "INVALID CREDENTIALS!");
        ps.setText("");
    }
  
            
    }//GEN-LAST:event_botlogMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel beach;
    private javax.swing.JPanel botlog;
    private javax.swing.JPanel container;
    private javax.swing.JTextField em;
    private javax.swing.JLabel emlabel;
    private javax.swing.JLabel eye;
    private javax.swing.JLabel forget;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel loghead;
    private javax.swing.JLabel login;
    private javax.swing.JDesktopPane mainpane;
    private javax.swing.JLabel passlabel;
    private javax.swing.JLabel people;
    private javax.swing.JPasswordField ps;
    private javax.swing.JLabel register;
    private javax.swing.JLabel van;
    // End of variables declaration//GEN-END:variables
}
