/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internalPages;

import config.config;
import java.awt.Color;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author RageKing
 */
public class updateForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form updateForm
     */
    public updateForm() {
        initComponents();
        
        loadUserAccounts();
        
        fullname.setText("");
        email.setText("");
        status.setText("");
        usersTable.clearSelection(); 
        
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
        
    }
    
    // Call this method when your admin dashboard form loads
public void loadUserAccounts() {
    try {
        config con = new config();
        String sql = "SELECT a_id, name, email, status FROM tbl_accounts WHERE type = 'USER'";
        con.displayData(sql, usersTable);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, 
            "Error loading accounts: " + e.getMessage());
    }
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        container = new javax.swing.JPanel();
        updatehead = new javax.swing.JLabel();
        backicon = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        usersTable = new javax.swing.JTable();
        container1 = new javax.swing.JPanel();
        emlabel = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        passlabel = new javax.swing.JLabel();
        eye = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        btnUpdate = new javax.swing.JPanel();
        update = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        fullname = new javax.swing.JTextField();
        status = new javax.swing.JTextField();
        statuslabel = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        container.setBackground(new java.awt.Color(209, 232, 243));
        container.setLayout(null);

        updatehead.setFont(new java.awt.Font("Arial Narrow", 1, 36)); // NOI18N
        updatehead.setForeground(new java.awt.Color(51, 153, 255));
        updatehead.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        updatehead.setText("UPDATE ACCOUNT");
        updatehead.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        container.add(updatehead);
        updatehead.setBounds(130, 0, 590, 80);

        backicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/backnobg.png"))); // NOI18N
        backicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backiconMouseClicked(evt);
            }
        });
        container.add(backicon);
        backicon.setBounds(10, 20, 90, 80);

        usersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        usersTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usersTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(usersTable);

        container.add(jScrollPane1);
        jScrollPane1.setBounds(90, 70, 704, 140);

        container1.setBackground(new java.awt.Color(209, 232, 243));
        container1.setLayout(null);

        emlabel.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        emlabel.setForeground(new java.awt.Color(51, 153, 255));
        emlabel.setText("Email*");
        container1.add(emlabel);
        emlabel.setBounds(350, 80, 270, 30);

        email.setForeground(new java.awt.Color(51, 153, 255));
        email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        container1.add(email);
        email.setBounds(350, 110, 200, 40);

        passlabel.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        passlabel.setForeground(new java.awt.Color(51, 153, 255));
        passlabel.setText("Password*");
        container1.add(passlabel);
        passlabel.setBounds(590, 80, 90, 30);

        eye.setBackground(new java.awt.Color(255, 255, 255));
        eye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/eye.png"))); // NOI18N
        eye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eyeMouseClicked(evt);
            }
        });
        container1.add(eye);
        eye.setBounds(760, 120, 30, 20);

        password.setForeground(new java.awt.Color(51, 153, 255));
        password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));
        container1.add(password);
        password.setBounds(590, 110, 200, 40);

        btnUpdate.setBackground(new java.awt.Color(152, 209, 247));
        btnUpdate.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUpdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUpdateMouseExited(evt);
            }
        });
        btnUpdate.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                btnUpdateInputMethodTextChanged(evt);
            }
        });
        btnUpdate.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        update.setBackground(new java.awt.Color(255, 255, 255));
        update.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        update.setText("Update account");
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateMouseClicked(evt);
            }
        });
        btnUpdate.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 40));

        container1.add(btnUpdate);
        btnUpdate.setBounds(350, 190, 450, 40);

        name.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        name.setForeground(new java.awt.Color(51, 153, 255));
        name.setText("Full Name*");
        container1.add(name);
        name.setBounds(90, 70, 160, 50);

        fullname.setForeground(new java.awt.Color(51, 153, 255));
        fullname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fullname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        fullname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullnameActionPerformed(evt);
            }
        });
        container1.add(fullname);
        fullname.setBounds(90, 110, 220, 40);

        status.setForeground(new java.awt.Color(51, 153, 255));
        status.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        status.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusActionPerformed(evt);
            }
        });
        container1.add(status);
        status.setBounds(90, 190, 200, 40);

        statuslabel.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        statuslabel.setForeground(new java.awt.Color(51, 153, 255));
        statuslabel.setText("Status*");
        container1.add(statuslabel);
        statuslabel.setBounds(90, 150, 160, 50);

        container.add(container1);
        container1.setBounds(0, 150, 860, 460);

        jPanel1.add(container, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 780));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backiconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backiconMouseClicked
        registerForm rf = new registerForm();
        rf.setVisible(true);
        dispose();

    }//GEN-LAST:event_backiconMouseClicked

    private void usersTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersTableMouseClicked

    int selectedRow = usersTable.getSelectedRow();
    
    if (selectedRow != -1) {
        fullname.setText(usersTable.getValueAt(selectedRow, 1).toString());
        email.setText(usersTable.getValueAt(selectedRow, 2).toString());
        status.setText(usersTable.getValueAt(selectedRow, 3).toString());
    }



    }//GEN-LAST:event_usersTableMouseClicked

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void eyeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eyeMouseClicked

        password.add(eye).setVisible(true);
    }//GEN-LAST:event_eyeMouseClicked

    private void updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseClicked

    int selectedRow = usersTable.getSelectedRow();
    
    // This is probably why it's not working - no row selected
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(null, 
            "Please select an account from the list first!", 
            "No Selection", 
            JOptionPane.WARNING_MESSAGE);
        return;
    }

    String aId = usersTable.getValueAt(selectedRow, 0).toString();
    String nameInput = fullname.getText().trim();
    String emailInput = email.getText().trim();
    String statusInput = status.getText().trim();

    if (nameInput.isEmpty() || emailInput.isEmpty() || statusInput.isEmpty()) {
        JOptionPane.showMessageDialog(null, 
            "All fields are required!", 
            "Validation Error", 
            JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (!emailInput.matches("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$")) {
        JOptionPane.showMessageDialog(null, 
            "Enter a valid email!\nExample: name@email.com", 
            "Validation Error", 
            JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        config con = new config();

        ResultSet rs = con.getData(
            "SELECT * FROM tbl_accounts WHERE email = ? AND a_id != ?", 
            emailInput, aId
        );

        if (rs != null && rs.next()) {
            JOptionPane.showMessageDialog(null, 
                "Email '" + emailInput + "' is already used!", 
                "Email Already Exists", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(null, 
            "Are you sure you want to update this account?", 
            "Confirm Update", 
            JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            con.updateRecord(
                "UPDATE tbl_accounts SET name = ?, email = ?, status = ? WHERE a_id = ?", 
                nameInput, emailInput, statusInput, aId
            );

            JOptionPane.showMessageDialog(null, 
                "Account Updated Successfully!", 
                "Success", 
                JOptionPane.INFORMATION_MESSAGE);

            // Refresh table
            loadUserAccounts();

            // Clear fields
            fullname.setText("");
            email.setText("");
            status.setText("");
            usersTable.clearSelection();
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, 
            "Error: " + e.getMessage(), 
            "Error", 
            JOptionPane.ERROR_MESSAGE);
        e.printStackTrace(); // Check the console for the exact error
    }

     
    }//GEN-LAST:event_updateMouseClicked

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked


    

    }//GEN-LAST:event_btnUpdateMouseClicked

    private void btnUpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseEntered
        btnUpdate.setBackground(new Color(51,102,255));
    }//GEN-LAST:event_btnUpdateMouseEntered

    private void btnUpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseExited
        btnUpdate.setBackground(new Color(152,209,247));
    }//GEN-LAST:event_btnUpdateMouseExited

    private void btnUpdateInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_btnUpdateInputMethodTextChanged

    }//GEN-LAST:event_btnUpdateInputMethodTextChanged

    private void fullnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullnameActionPerformed

    private void statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backicon;
    private javax.swing.JPanel btnUpdate;
    private javax.swing.JPanel container;
    private javax.swing.JPanel container1;
    private javax.swing.JTextField email;
    private javax.swing.JLabel emlabel;
    private javax.swing.JLabel eye;
    private javax.swing.JTextField fullname;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel name;
    private javax.swing.JLabel passlabel;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField status;
    private javax.swing.JLabel statuslabel;
    private javax.swing.JLabel update;
    private javax.swing.JLabel updatehead;
    private javax.swing.JTable usersTable;
    // End of variables declaration//GEN-END:variables
}
