/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internalPages;

import config.config;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author RageKing
 */
public class userforms extends javax.swing.JInternalFrame {

    /**
     * Creates new form userforms
     */
    public userforms() {
        initComponents();
         displayUser();
 
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
    }
    
    public void displayUser(){
        
        config cn = new config();
        String sql = "SELECT * FROM tbl_accounts";
        cn.displayData(sql, usertable);
                
        
    }
    
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mainpane = new javax.swing.JDesktopPane();
        container = new javax.swing.JPanel();
        search = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        update = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        delete = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        add = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        searchkey = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        usertable = new javax.swing.JTable();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        mainpane.setBackground(new java.awt.Color(209, 232, 243));

        container.setBackground(new java.awt.Color(209, 232, 243));
        container.setLayout(null);

        search.setBackground(new java.awt.Color(0, 153, 255));
        search.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchMouseClicked(evt);
            }
        });
        search.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("SEARCH");
        search.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 7, 120, 30));

        container.add(search);
        search.setBounds(690, 40, 130, 40);

        update.setBackground(new java.awt.Color(0, 153, 255));
        update.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateMouseClicked(evt);
            }
        });
        update.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("UPDATE");
        update.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 7, 120, 30));

        container.add(update);
        update.setBounds(160, 40, 130, 40);

        delete.setBackground(new java.awt.Color(0, 153, 255));
        delete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
        });
        delete.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("DELETE");
        delete.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 7, 120, 30));

        container.add(delete);
        delete.setBounds(310, 40, 130, 40);

        add.setBackground(new java.awt.Color(0, 153, 255));
        add.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
        });
        add.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADD");
        add.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 7, 120, 30));

        container.add(add);
        add.setBounds(10, 40, 130, 40);

        searchkey.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        searchkey.setCaretColor(new java.awt.Color(0, 153, 255));
        searchkey.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchkeyMouseClicked(evt);
            }
        });
        searchkey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchkeyActionPerformed(evt);
            }
        });
        container.add(searchkey);
        searchkey.setBounds(450, 40, 230, 40);

        usertable.setAutoCreateRowSorter(true);
        usertable.setBackground(new java.awt.Color(209, 232, 243));
        usertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        usertable.setGridColor(new java.awt.Color(209, 232, 243));
        usertable.setSelectionBackground(new java.awt.Color(209, 232, 243));
        usertable.setSelectionForeground(new java.awt.Color(209, 232, 243));
        jScrollPane1.setViewportView(usertable);

        container.add(jScrollPane1);
        jScrollPane1.setBounds(10, 90, 810, 310);

        mainpane.setLayer(container, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout mainpaneLayout = new javax.swing.GroupLayout(mainpane);
        mainpane.setLayout(mainpaneLayout);
        mainpaneLayout.setHorizontalGroup(
            mainpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE)
        );
        mainpaneLayout.setVerticalGroup(
            mainpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
        );

        jPanel1.add(mainpane);
        mainpane.setBounds(0, 0, 840, 420);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 840, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchkeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchkeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchkeyActionPerformed

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
         registerForm rf = new registerForm();
        mainpane.add(rf).setVisible(true);
         
    }//GEN-LAST:event_addMouseClicked

    private void updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseClicked
         updateForm rf = new updateForm();
        mainpane.add(rf).setVisible(true);
    }//GEN-LAST:event_updateMouseClicked

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
         deleteForm df = new deleteForm();
        mainpane.add(df).setVisible(true);
    }//GEN-LAST:event_deleteMouseClicked

    private void searchkeyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchkeyMouseClicked

    }//GEN-LAST:event_searchkeyMouseClicked

    private void searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseClicked

    String searchInput = searchkey.getText().trim(); // Change txtSearch to your actual search field name

    // Check if search field is empty
    if (searchInput.isEmpty()) {
        JOptionPane.showMessageDialog(null, 
            "Please enter something to search!", 
            "Empty Search", 
            JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        config con = new config();

        // Search by name or email
        String sql = "SELECT a_id, name, email, status FROM tbl_accounts WHERE type = 'USER' " +
                     "AND (name LIKE ? OR email LIKE ?)";
        
        ResultSet rs = con.getData(sql, 
            "%" + searchInput + "%",  // Search name
            "%" + searchInput + "%"   // Search email
        );

        if (rs != null && rs.next()) {
            // Found - load results into table
            // Reset cursor to beginning
            // We need to re-run the query to load into table
            con.displayData(
                "SELECT a_id, name, email, status FROM tbl_accounts WHERE type = 'USER' " +
                "AND (name LIKE '" + searchInput + "%' OR email LIKE '" + searchInput + "%')", 
              usertable // Change Table to your actual JTable name
            );
        } else {
            // Not found
            JOptionPane.showMessageDialog(null, 
                "No account found for '" + searchInput + "'!", 
                "Not Found", 
                JOptionPane.INFORMATION_MESSAGE);
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, 
            "Error: " + e.getMessage(), 
            "Error", 
            JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_searchMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel add;
    private javax.swing.JPanel container;
    private javax.swing.JPanel delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JDesktopPane mainpane;
    private javax.swing.JPanel search;
    private javax.swing.JTextField searchkey;
    private javax.swing.JPanel update;
    private javax.swing.JTable usertable;
    // End of variables declaration//GEN-END:variables
}
