/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package superadmin;

import config.config;
import internalPages.registerForm;
import java.awt.Color;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author RageKing
 */
public class addadmin extends javax.swing.JInternalFrame {

    /**
     * Creates new form addadmin
     */
    public addadmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        container = new javax.swing.JPanel();
        loghead = new javax.swing.JLabel();
        emlabel = new javax.swing.JLabel();
        em = new javax.swing.JTextField();
        passlabel = new javax.swing.JLabel();
        eye = new javax.swing.JLabel();
        ps = new javax.swing.JPasswordField();
        botcreate = new javax.swing.JPanel();
        create = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        fullname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        container.setBackground(new java.awt.Color(209, 232, 243));
        container.setLayout(null);

        loghead.setFont(new java.awt.Font("Arial Narrow", 1, 36)); // NOI18N
        loghead.setForeground(new java.awt.Color(51, 153, 255));
        loghead.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loghead.setText("ADD ADMIN ACCOUNT");
        loghead.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        container.add(loghead);
        loghead.setBounds(150, 0, 590, 80);

        emlabel.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        emlabel.setForeground(new java.awt.Color(51, 153, 255));
        emlabel.setText("Email*");
        container.add(emlabel);
        emlabel.setBounds(240, 170, 270, 30);

        em.setForeground(new java.awt.Color(51, 153, 255));
        em.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        em.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        em.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emActionPerformed(evt);
            }
        });
        container.add(em);
        em.setBounds(240, 200, 450, 40);

        passlabel.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        passlabel.setForeground(new java.awt.Color(51, 153, 255));
        passlabel.setText("Password*");
        container.add(passlabel);
        passlabel.setBounds(240, 250, 90, 30);

        eye.setBackground(new java.awt.Color(255, 255, 255));
        eye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/eye.png"))); // NOI18N
        eye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eyeMouseClicked(evt);
            }
        });
        container.add(eye);
        eye.setBounds(650, 290, 30, 20);

        ps.setForeground(new java.awt.Color(51, 153, 255));
        ps.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ps.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));
        container.add(ps);
        ps.setBounds(240, 280, 450, 40);

        botcreate.setBackground(new java.awt.Color(152, 209, 247));
        botcreate.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botcreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botcreateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botcreateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botcreateMouseExited(evt);
            }
        });
        botcreate.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                botcreateInputMethodTextChanged(evt);
            }
        });
        botcreate.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        create.setBackground(new java.awt.Color(255, 255, 255));
        create.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        create.setForeground(new java.awt.Color(255, 255, 255));
        create.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        create.setText("Create account");
        create.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createMouseClicked(evt);
            }
        });
        botcreate.add(create, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 40));

        container.add(botcreate);
        botcreate.setBounds(240, 350, 450, 40);

        name.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        name.setForeground(new java.awt.Color(51, 153, 255));
        name.setText("Full Name*");
        container.add(name);
        name.setBounds(240, 70, 160, 50);

        fullname.setForeground(new java.awt.Color(51, 153, 255));
        fullname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fullname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        fullname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullnameActionPerformed(evt);
            }
        });
        container.add(fullname);
        fullname.setBounds(240, 120, 450, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/backnobg.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        container.add(jLabel2);
        jLabel2.setBounds(10, 20, 90, 80);

        jPanel2.add(container, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 420));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emActionPerformed

    private void eyeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eyeMouseClicked

        ps.add(eye).setVisible(true);
    }//GEN-LAST:event_eyeMouseClicked

    private void createMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createMouseClicked
        String nameInput = fullname.getText().trim();
        String emailInput = em.getText().trim();
        String passwordInput = ps.getText().trim();

        // Check if fields are empty
        if (nameInput.isEmpty() || emailInput.isEmpty() || passwordInput.isEmpty()) {
            JOptionPane.showMessageDialog(null,
                "All fields are required!",
                "Validation Error",
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Check email format
        if (!emailInput.matches("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$")) {
            JOptionPane.showMessageDialog(null,
                "Enter a valid email!\nExample: name@email.com",
                "Validation Error",
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Check password length
        if (passwordInput.length() < 6) {
            JOptionPane.showMessageDialog(null,
                "Password must be at least 6 characters!",
                "Validation Error",
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            config con = new config();

            // Check if email already exists
            ResultSet rs = con.getData("SELECT * FROM tbl_accounts WHERE email = ?", emailInput);

            if (rs != null && rs.next()) {
                JOptionPane.showMessageDialog(null,
                    "Email '" + emailInput + "' already exists!\nUse a different email.",
                    "Email Already Exists",
                    JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Insert record
            con.addRecord(
                "INSERT INTO tbl_accounts (name, email, password, type, status) VALUES (?, ?, ?, ?, ?)",
                nameInput, emailInput, passwordInput, "ADMIN", "ACTIVE"
            );

            JOptionPane.showMessageDialog(null,
                "Account Created Successfully!",
                "Success",
                JOptionPane.INFORMATION_MESSAGE);

            // Clear fields
            fullname.setText("");
            em.setText("");
            ps.setText("");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,
                "Error: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_createMouseClicked

    private void botcreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botcreateMouseClicked

    }//GEN-LAST:event_botcreateMouseClicked

    private void botcreateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botcreateMouseEntered
        botcreate.setBackground(new Color(51,102,255));
    }//GEN-LAST:event_botcreateMouseEntered

    private void botcreateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botcreateMouseExited
        botcreate.setBackground(new Color(152,209,247));
    }//GEN-LAST:event_botcreateMouseExited

    private void botcreateInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_botcreateInputMethodTextChanged

    }//GEN-LAST:event_botcreateInputMethodTextChanged

    private void fullnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullnameActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        superadminDashboard sd  = new superadminDashboard();
        sd.setVisible(true);
        dispose();

    }//GEN-LAST:event_jLabel2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botcreate;
    private javax.swing.JPanel container;
    private javax.swing.JLabel create;
    private javax.swing.JTextField em;
    private javax.swing.JLabel emlabel;
    private javax.swing.JLabel eye;
    private javax.swing.JTextField fullname;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel loghead;
    private javax.swing.JLabel name;
    private javax.swing.JLabel passlabel;
    private javax.swing.JPasswordField ps;
    // End of variables declaration//GEN-END:variables
}
