/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import config.Session;
import internalPages.*;
import internalPages.userforms;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author RageKing
 */
public class adminDashboard extends javax.swing.JInternalFrame {

    /**
     * Creates new form adminDashboard
     */
    public adminDashboard() {
        initComponents();
         
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
        
        
        
    }
    
 
    

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        adhead = new javax.swing.JLabel();
        nav = new javax.swing.JPanel();
        users = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        booking = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        logout = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        fleet = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        profile = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        addheadpanel = new javax.swing.JPanel();
        mainpane = new javax.swing.JDesktopPane();
        container = new javax.swing.JPanel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adhead.setBackground(new java.awt.Color(51, 153, 255));
        adhead.setFont(new java.awt.Font("Arial Narrow", 1, 36)); // NOI18N
        adhead.setForeground(new java.awt.Color(0, 0, 204));
        adhead.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adhead.setText("ADMIN DASHBOARD");
        jPanel1.add(adhead, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 14, 830, 90));

        nav.setBackground(new java.awt.Color(39, 168, 255));
        nav.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        users.setBackground(new java.awt.Color(102, 153, 255));
        users.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                usersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                usersMouseExited(evt);
            }
        });
        users.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("USERS");
        users.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, -1, 170, 60));

        nav.add(users, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 180, 60));

        booking.setBackground(new java.awt.Color(102, 153, 255));
        booking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bookingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bookingMouseExited(evt);
            }
        });
        booking.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("BOOKING");
        booking.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -1, 180, 60));

        nav.add(booking, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 180, 60));

        logout.setBackground(new java.awt.Color(102, 153, 255));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });
        logout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("LOGOUT");
        logout.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 60));

        nav.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 180, 60));

        fleet.setBackground(new java.awt.Color(102, 153, 255));
        fleet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fleetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fleetMouseExited(evt);
            }
        });
        fleet.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("FLEET");
        fleet.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 60));

        nav.add(fleet, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 180, 60));

        profile.setBackground(new java.awt.Color(102, 153, 255));
        profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                profileMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                profileMouseExited(evt);
            }
        });
        profile.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("PROFILE");
        profile.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 60));

        nav.add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 180, 59));

        jPanel1.add(nav, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 180, -1));

        addheadpanel.setBackground(new java.awt.Color(102, 204, 255));

        javax.swing.GroupLayout addheadpanelLayout = new javax.swing.GroupLayout(addheadpanel);
        addheadpanel.setLayout(addheadpanelLayout);
        addheadpanelLayout.setHorizontalGroup(
            addheadpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
        );
        addheadpanelLayout.setVerticalGroup(
            addheadpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(addheadpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1020, -1));

        mainpane.setBackground(new java.awt.Color(102, 204, 255));

        container.setBackground(new java.awt.Color(209, 232, 243));
        container.setLayout(null);
        mainpane.add(container);
        container.setBounds(0, 0, 830, 380);

        jPanel1.add(mainpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 830, 450));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -16, 1010, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersMouseEntered
       users.setBackground(new Color(209,232,243));
    }//GEN-LAST:event_usersMouseEntered

    private void usersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersMouseExited
       users.setBackground(new Color(102,153,255));
    }//GEN-LAST:event_usersMouseExited

    private void bookingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookingMouseEntered
         booking.setBackground(new Color(209,232,243));
    }//GEN-LAST:event_bookingMouseEntered

    private void bookingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookingMouseExited
        booking.setBackground(new Color(102,153,255));
    }//GEN-LAST:event_bookingMouseExited

    private void fleetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fleetMouseEntered
        fleet.setBackground(new Color(209,232,243));
    }//GEN-LAST:event_fleetMouseEntered

    private void fleetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fleetMouseExited
        fleet.setBackground(new Color(102,153,255));
    }//GEN-LAST:event_fleetMouseExited

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        logout.setBackground(new Color(209,232,243));
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
        logout.setBackground(new Color(102,153,255));
    }//GEN-LAST:event_logoutMouseExited

    private void usersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersMouseClicked
        users.setBackground(new Color(209,232,243));
        userforms us = new userforms();
        mainpane.add(us).setVisible(true);
      
    }//GEN-LAST:event_usersMouseClicked

    private void profileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileMouseEntered
        profile.setBackground(new Color(209,232,243));
    }//GEN-LAST:event_profileMouseEntered

    private void profileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileMouseExited
        profile.setBackground(new Color(102,153,255));
    }//GEN-LAST:event_profileMouseExited

    private void profileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileMouseClicked
         adminProfile ap = new adminProfile();
        mainpane.add(ap).setVisible(true);
    }//GEN-LAST:event_profileMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addheadpanel;
    private javax.swing.JLabel adhead;
    private javax.swing.JPanel booking;
    private javax.swing.JPanel container;
    private javax.swing.JPanel fleet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel logout;
    private javax.swing.JDesktopPane mainpane;
    private javax.swing.JPanel nav;
    private javax.swing.JPanel profile;
    private javax.swing.JPanel users;
    // End of variables declaration//GEN-END:variables
}
